### PR TITLE
Fix bug in `rainbow-colorize-ansi'

### PR DESCRIPTION
**Pull request by Alexander-Shukaev**
Fixes interoperability issue tarsius/hl-todo#17.

### CODE REVIEW

**Comment by Alexander-Shukaev** [comment]
@jd
@tarsius

**Comment by Alexander-Shukaev** [comment]
Shall we merge this?

**Comment by tarsius** [comment]
Well I guess I asked for this by opening pull-requests in this repository myself, but this is only a mirror and I do not merge any pull-requests. Please contact the maintainer instead. And don't do what I have done in #3 - send an email instead.

**Comment by Alexander-Shukaev** [comment]
[Merged](http://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=commit;h=fd29bf732f488c42cff35fcb54be31021e311e06) .

**Pull request closed without merging**
