### PR TITLE
Various minor changes

### PR DESCRIPTION
**Pull request by tarsius**
@jd 

Please see the commit messages.

I believe I send a mail about the first two commits to `emacs-devel` or `debbugs` a few months ago, but could not find that anymore. Even if I did, you probably didn't see it.

Could you please apply these changes on `rainbow-mode`'s repository and then merge that into `elpa` too? Thanks a lot!

### CODE REVIEW

**Comment by tarsius** [comment]
Friendly ping!

**Comment by tarsius** [comment]
This doesn't appear to be the right channel either, so I am closing this.

**Comment by jd** [comment]
@tarsius it's not but the alternative is email so don't worry. I'll take a look!

**Comment by jd** [comment]
@tarsius your patches looks good and I'm ok to merge them. Could you do them on top of the ELPA repository (https://savannah.gnu.org/git/?group=emacs) and send them to me via e.g. email or a git request-pull or whatever. :)

**Pull request closed without merging**
